spring.application.name=VertexLib

spring.datasource.url=jdbc:postgresql://localhost:5432/vertex_lib
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=dGhpcyBpcyBhIHNlY3VyZSAyNTYtYml0IHNlY3JldCBrZXkgZm9yIFZlcnRleExpYiE=
# Token muddati: 24 soat (millisekund)
jwt.expiration=86400000
